fix: eslint expected linebreaks updated
flybywiresim/react-components pull request #7
Opened 2021-05-25 06:52 UTC by antonyisoardi

Issue: https://github.com/flybywiresim/a32nx/issues/4761

PR is currently WIP

2021-05-27 18:23 UTC, Benjozork requested changes

2021-05-27 18:23 UTC, Benjozork commented on src/Map/Map.scss
> +  #control-panel {
Use tailwind as much as possible

2021-05-30 07:52 UTC, Benjozork commented
Make sure you don't have purging enabled

2021-05-30 07:52 UTC, Benjozork approved these changes

2021-05-31 03:53 UTC, antonyisoardi commented
> Make sure you don't have purging enabled

Hey @Benjozork - can you please elaborate on this one?

2021-05-31 04:10 UTC, Benjozork commented
If some tailwind classes don't work you might have purging enabled.

2021-06-01 12:02 UTC, antonyisoardi commented
@Benjozork what else needs to happen for this to get merged?

2021-06-01 18:19 UTC, Benjozork commented
I'll test it locally today and get it merged.

2021-06-01 21:54 UTC, Benjozork commented
@antonyisoardi Found the issue with classes not working.

Purging is force-enabled:

![image](https://user-images.githubusercontent.com/4503241/120395002-4763b600-c302-11eb-9e75-653b3c7e4978.png)

Since purging is not run on every webpack build, previously unused classes are not kept.

I'll make a PR to change this after merging this one.

This did not affect production builds.

2021-06-01 22:10 UTC, merged